version: '3'
services:
  mariadb:
    build:  ./mariadb
    ports:
     - "3306"
    volumes:
     - "/home/user42/volumes"
    restart: always
  wordpress:
    depends_on:
     - mariadb
    build: ./wordpress
    ports:
     - "9000:9000"
    volumes:
     - "/home/user42/volumes"
    restart: always
  nginx:
    build:  ./nginx
    ports:
     - "443:443"
     - "80:80"
    restart: unless-stopped
    volumes:
     - "/home/user42/volumes"
    depends_on:
     - wordpress

networks:
  first:
   driver: overlay
        
volumes:
 db_data: {}

