version: '3.5'
services:
  mariadb:
    build:  ./mariadb
    container_name: mariadb_kejebane
    networks:
     - zeibel
    expose:
     - "3306"
    volumes:
     - "/home/user42/volumes"
    env_file: ./.env
    restart: always


      #-------------------------------------#


  wordpress:
    depends_on:
     - mariadb
    build: ./wordpress
    container_name: wp_kejebane
    networks:
     - zeibel
    expose:
     - "9000"
    volumes:
     - "/home/user42/volumes"
    restart: always
    env_file: ./.env


      #-------------------------------------#


  nginx:
    build:  ./nginx
    container_name: nginx_kejebane
    networks:
     - zeibel
    ports:
     - "443:443"
    restart: unless-stopped
    tty: true
    env_file: ./.env
    volumes:
     - "/home/user42/volumes"
    depends_on:
     - wordpress

      #-------------------------------------#

networks:
  zeibel:
    external: true
    name: zeibel
    driver: bridge
        
volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/user42/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/user42/data/mariadb

      #volumes:
      #db_data: {}

